#   Copyright 2021 Philipp Weber
#   
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   
#       http://www.apache.org/licenses/LICENSE-2.0
#   
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

name: chirpstack-application-server

on: 
    push:
    schedule:
    - cron: '0 3 * * 1,5'   # every Monday and Friday at 3am

jobs:
    create-container:
        name: Create chirpstack-application-server multiarch container
        runs-on: ubuntu-latest
        steps:
          - name: Get latest chirpstack-application-server release tag
            id: chirpstack-application-server-latest
            uses: pozetroninc/github-action-get-latest-release@master
            with:
              repository: brocaar/chirpstack-application-server
              excludes: prerelease, draft
        
          - name: Check-out chirpstack-application-server-latest
            uses: actions/checkout@v2
            with:
                repository: brocaar/chirpstack-application-server
                ref: ${{ steps.chirpstack-application-server-latest.outputs.release }}

          - name: Modify dockerfile for multiarch builds
            run: |
                 sed -i 's/FROM g/FROM --platform=$BUILDPLATFORM g/' Dockerfile
                 sed -i 's/RUN make/COPY --from=tonistiigi\/xx:golang \/ \/\nARG TARGETPLATFORM\nRUN make/' Dockerfile
        
          - name: Set-up QEMU
            uses: docker/setup-qemu-action@v1
        
          - name: Set-up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1
        
          - name: List available platforms
            run: echo ${{ steps.buildx.outputs.platforms }}
        
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
        
          - name: Build and push container
            uses: docker/build-push-action@v2
            with:
                context: .
                platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/chirpstack-application-server:${{ steps.chirpstack-application-server-latest.outputs.release }}
